"""Added enabled boolean

Revision ID: 2e2d705bd238
Revises: dc8b9fdfde28
Create Date: 2018-05-28 19:37:59.162866

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = '2e2d705bd238'
down_revision = 'dc8b9fdfde28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitors', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monitors', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
