"""First data model

Revision ID: 97babb0e63e6
Revises: 
Create Date: 2018-05-27 17:15:55.592928

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = '97babb0e63e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=False),
    sa.Column('server', sa.String(length=256), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('verb', sa.Enum('GET', 'POST', 'PUT', 'DELETE', name='httpverb'), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('headers', sqlalchemy_json.MutableJson(), nullable=True),
    sa.CheckConstraint('port > 0 AND port < 65536', name='valid_port_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_slug'), 'monitors', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitors_slug'), table_name='monitors')
    op.drop_table('monitors')
    # ### end Alembic commands ###
