"""Added enabled boolean

Revision ID: dc8b9fdfde28
Revises: 97babb0e63e6
Create Date: 2018-05-28 19:31:23.269415

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_json


# revision identifiers, used by Alembic.
revision = 'dc8b9fdfde28'
down_revision = '97babb0e63e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('enabled', sa.Boolean(name='monitor_enabled'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitors', 'enabled')
    # ### end Alembic commands ###
